# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weather_mositure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='mositure',
            new_name='moisture',
        ),
    ]
