# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20171005_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Waterlevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.CharField(max_length=10)),
                ('bucket', models.CharField(max_length=10)),
                ('water_level', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='weather',
            name='moisture',
        ),
    ]
