# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_plant_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='plantid',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='location',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='check',
        ),
        migrations.AddField(
            model_name='plant',
            name='latitude',
            field=models.CharField(default=13.5372058, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='longitude',
            field=models.CharField(default=79.9982069, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='check',
            field=models.CharField(default='no rain', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.plantid'),
        ),
    ]
