# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_auto_20171103_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='latitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='longitude',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
