# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_auto_20171104_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantid',
            name='latitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plantid',
            name='longitude',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
