# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='mositure',
            field=models.CharField(default=1000, max_length=10),
            preserve_default=False,
        ),
    ]
