# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20171006_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterlevel',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='waterlevel',
            name='reading',
        ),
    ]
