# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_auto_20171104_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='longitude',
        ),
    ]
